### ISSUE TITLE
[feature request] -d option in conbination with -1 

### ISSUE THREAD

**Issue by dl4ner** [walterdejong/synctool#42]
Hi Walter, 

I often have to use 
`synctool -d filename`
to check the differences and see if it is really a good idea to overwrite the changed content with the (maybe) stale content of the synctool repository. 

I'd suggest supporting -d without additional parameter - if -1 is uses.
then one would be able to do this:

`synctool -n node1 -1 /path/to/changed/file -d`
`synctool -n node1 -1 /path/to/changed/file -f'`

this would be much easier to handle in cmdline with cmdline histories ;)

cheers 
    Werner

**Comment by walterdejong** [comment]
I see what you mean.
Unfortunately, the `getopt` command line option parser won't allow this, because it expects an argument after `-d`. I would have to make a pretty awesome hack to enable this.

Maybe we could have this though:

    synctool -n node1 -d /path/to/changed/file -f

but I'm a bit afraid it would only lead to mistakes and confusion.
So I'm inclined to close this ticket as "wontfix".

**Comment by walterdejong** [comment]
note: commit 8916c89 is very untested at this moment

**Comment by walterdejong** [comment]
It's working alright.
I think there was another commit involved as well ... anyway, fixed.
