### ISSUE TITLE
Sync Interval And Node Discovery

### ISSUE THREAD

**Issue by Zelda66** [walterdejong/synctool#52]
Hello thank you for the great project. I am thinking of using synctool for managing my linux clients. I have a few issues about synctool

1) Should i trigger from server for syncing files between master and nodes, or does it auto sync within some intervals? Should i assign a cronjob for this?

2) What would you suggest for discovering nodes, how can i auto add client nodes and start managing?

I'll very happy if you answer, best regards.
Zelda,

**Comment by walterdejong** [comment]
Hi Zelda66,

1. It does not auto-sync, and although you _can_ assign a cronjob for this, I would not recommend this. Unlike many tools that forcibly apply changes, synctool takes a more careful approach and allows you to review changes. And then you make the decision to apply the change. This is a manual action, but at least it is _you_ who keeps control over what the tool is doing. It can be automated, but it takes away the carefulness and the level of control.

2. One does not typically discover nodes (?) Since you are the sysadmin, you should know what nodes there are, and register them in the config file. If there are many, many nodes, there is likely to be some kind of numbering scheme in place and you can shorten the config by using a syntax for enumerating sequences. Other than that, you might use `nmap -sP` to scan the private network. To automatically add them to the config, you would have to do some scripting, e.g. with `awk`.

Thanks & greets

**Comment by Zelda66** [comment]
Thank you very much Walter, i will apply you suggestions, but my actual main concern is i want newly installed linux client should get configurations with very first boot. I can continue without cron job after. How can i do acomplish that?

Best regards.

**Comment by walterdejong** [comment]
It depends on whether you have a good bare metal installer set up or not. If you do, you can do this:

* put the `/root/.ssh/authorized_keys` file in place on the target node during the installation
* `rsync -ar /opt/synctool/` to the target node
* run `synctool-client -f` on the target node. You can make an init-script to have it run at boot time, or you can just run it at the end of the installation

synctool does not use a pull-model. Client-pull does not fit the philosophy that changes must be reviewed and applied with care.

**Comment by Zelda66** [comment]
Thank you very much Walter, its nice to know i have a good "synctool-client" option. So i am trying to use synctool pull based approach. I will create groups testing and production for each policy i.e, when my policy is right i will add nodes to production. As your comment i will trigger synctool-client from client on init and maybe a cron job after. Would there be any other cons for this pull approch?

**Comment by walterdejong** [comment]
A "con" is that if you edit the repository directly, which most people do, then there exists a scenario in which a client automatically pulls in a half-finished config. This gives a certain risk of breaking stuff.
