### ISSUE TITLE
Automate package handling

### ISSUE THREAD

**Issue by fancsali** [walterdejong/synctool#53]
I was just wondering about something, and I feel, is missing from **synctool**. I thought I'd share my ideas, just in case, someone else is interested.

So, consider the following scenario:

I want to configure **apache**, so I add `/etc/httpd.conf` (or whatever my preferred distro calls the file...) to the `overlay` directory. Then I'd add a `.pre` script, that would call `synctool-client-pkg` to ensure, apache is actually installed. And a `.post` to restart apache if there was a config change. That's all fine and dandy, a missing config file would trigger the install, "upload" the config file, and then restart the service.

However, what if, just for the sake of the argument, I am running a hosting service, and I want to ensure certain PHP and/or Python libraries are installed (and up to date) for my customers, but I am happy with the default config. I reckon, I have no way of triggering this when running `synctool` or `synctool-client`.

I'd like to propose a new directory (alongside the `overlay`/`delete`/`purge` and `task` ones), that would contain empty files, with the names of the packages that should be installed; of course abiding by the current rules of groups and all.

As a further enhancement, I think, there is a case for allowing tagging of the files (similar to the `_template` tag) to use a specific package manager instead of the default for the node. This would allow for example installing `pip` with the default package manager, and then use pip to install Python packages.

Or, generalising the idea even further, there could be a way of defining hooks: Applying the usual rules, the files matching the current node would be interpreted as task names, and automatically called upon running `synctool` or `synctool-client`; STDIN and/or arguments for the script could come from the content of the file, very similar to how templates are handled.

**Comment by walterdejong** [comment]
What you are proposing very much resembles "synctool tasks", which was a feature in synctool 5, but was dropped in synctool 6 because `dsh` already does all that.

The way to solve package installations as you describe it goes as follows:

* put a file on the target system that lists the packages. (The source file goes in synctool/overlay/)
* put a very small shell script on the system that installs everything listed in the file. (The source goes either in synctool/overlay/ or synctool/scripts/)
* use `dsh` to run the script on the target system

You can use the same strategy for pip installs.
(Be warned: I've systems break because pip was used by root outside a virtualenv).

**Comment by fancsali** [comment]
I see.

The reason this came up is, that I was trying to get to a setup, where one single command would rebuild an instance for me. I reckon, the most appropriate way to do that would be to create a script, that I call via `dsh`, which does all the magic with installing things, and then also calls `synctool-client` to actually configure everything.
